### ISSUE TITLE
upkeep: Add `CODEOWNERS` file with maintainer

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.ca100.analysis#2]
@Antoine-Lalechere I guess that would be you?

**Comment by Antoine-Lalechere** [comment]
I think so, I can take care of this in the next sprint - do you have a tuto explaining how to create cleanly a CODEOWNERS file?

**Comment by jdhoffa** [comment]
This PR should be a good template:
https://github.com/RMI-PACTA/workflow.scenario.preparation/pull/2

(No urgency at all in doing this, just general house-keeping 😃 )

**Comment by Antoine-Lalechere** [comment]
closed by #3
